#!/usr/bin/env python3
"""Generate EXP-06 round-2 swanctl configs: testbed/configs/exp06/{alice,bob}.conf

Each failure arm gets its OWN alias address pair (alice 10.10.1.10k, bob
10.10.2.10k), used as both the IKE endpoints and the traffic selectors, so no two
arms can share an XFRM policy or be confused by the responder's
address/identity-based config selection. That was the round-1 flaw — see
experiments/exp06-failure-diagnosis/RESULT.md.

IKE identities are a fixed 5 characters (a-f0k / b-f0k) to remove round 1's
ID-length confound inside the encrypted IKE_AUTH messages.

Pre-registered design and predictions: research/registers/EXPERIMENT-REGISTER.md
("EXP-06 Round 2 — PRE-REGISTRATION").
"""
import json
import pathlib

OUT = pathlib.Path(__file__).parent.parent / "configs" / "exp06"
GOOD_PSK = "0sIhtestlab2026SIH26160presharedkeydonotusehere"
BAD_PSK = "0sWRONGwrongWRONGwrongWRONGwrongWRONGwrongWRONG0"  # F4 only, bob side

BASE = dict(ike="aes256-sha256-modp2048", esp="aes256gcm16")

# k: (label, alice-side overrides, bob-side overrides)
ARMS = {
    0: ("F0-success",              {}, {}),
    1: ("F1-ike-proposal",         {}, {"ike": "aes128-sha256-ecp256"}),
    2: ("F2-child-proposal",       {}, {"esp": "aes128-sha256"}),
    3: ("F3-ts-mismatch",          {}, {"remote_ts": "10.10.1.199/32"}),
    4: ("F4-auth-fail",            {}, {"psk": BAD_PSK}),
    5: ("F5-pfs-mismatch",         {"esp": "aes256gcm16-modp2048"}, {}),
    6: ("F6-unreachable",          {"remote_addr": "10.10.2.199"}, None),  # bob has no config
}


def addr(side, k):
    return f"10.10.{1 if side == 'alice' else 2}.{100 + k}"


def conn_block(k, side, ov):
    me, peer = ("alice", "bob") if side == "alice" else ("bob", "alice")
    local = addr(me, k)
    remote = ov.get("remote_addr", addr(peer, k))
    lid, rid = f"{me[0]}-f{k:02d}", f"{peer[0]}-f{k:02d}"
    remote_ts = ov.get("remote_ts", f"{addr(peer, k)}/32")
    name = f"f{k:02d}"
    return f"""    {name} {{
        local_addrs  = {local}
        remote_addrs = {remote}
        local {{
            auth = psk
            id = {lid}
        }}
        remote {{
            auth = psk
            id = {rid}
        }}
        version = 2
        proposals = {ov.get('ike', BASE['ike'])}
        children {{
            {name} {{
                local_ts = {local}/32
                remote_ts = {remote_ts}
                mode = tunnel
                esp_proposals = {ov.get('esp', BASE['esp'])}
                start_action = none
                dpd_action = clear
                life_time = 3600
                rekey_time = 0
            }}
        }}
    }}
"""


def secret_block(k, side, ov):
    me, peer = ("alice", "bob") if side == "alice" else ("bob", "alice")
    return f"""    ike-f{k:02d} {{
        id-1 = {me[0]}-f{k:02d}
        id-2 = {peer[0]}-f{k:02d}
        secret = "{ov.get('psk', GOOD_PSK)}"
    }}
"""


def render(side):
    conns, secrets = [], []
    for k, (label, a_ov, b_ov) in ARMS.items():
        ov = a_ov if side == "alice" else b_ov
        if ov is None:
            continue
        conns.append(f"    # {label}\n" + conn_block(k, side, ov))
        secrets.append(secret_block(k, side, ov))
    return (f"# AUTO-GENERATED by testbed/scripts/gen_exp06_conf.py — EXP-06 round 2 ({side}). Do not hand-edit.\n"
            "connections {\n" + "".join(conns) + "}\n\nsecrets {\n" + "".join(secrets) + "}\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for side in ("alice", "bob"):
        (OUT / f"{side}.conf").write_text(render(side))
    manifest = {f"f{k:02d}": {"label": lab, "alice_alias": addr("alice", k),
                               "bob_alias": a.get("remote_addr", addr("bob", k)),
                               "alice_overrides": a, "bob_overrides": b}
                for k, (lab, a, b) in ARMS.items()}
    (OUT / "arms.json").write_text(json.dumps(manifest, indent=2))
    print(f"Wrote {len(ARMS)} arms to {OUT}")


if __name__ == "__main__":
    main()
