#!/usr/bin/env python3
"""Generate testbed/configs/{alice,bob}/swanctl.conf from experiment_matrix.json.

This is the single source of truth for testbed IPsec configuration — do not
hand-edit the generated swanctl.conf files. Regenerate with:

    python3 testbed/scripts/gen_swanctl_conf.py

Reproducibility: the matrix file, this script, and the strongSwan/Docker
versions recorded in testbed/MANIFEST.md together fully determine the
generated configuration. No randomness is involved in config generation.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
MATRIX_PATH = HERE / "experiment_matrix.json"
CONFIGS_DIR = HERE.parent / "configs"

HEADER = """\
# AUTO-GENERATED by testbed/scripts/gen_swanctl_conf.py from
# testbed/scripts/experiment_matrix.json. Do not hand-edit.
# Role: {role}
"""


def render_connection(name: str, mode: str, esp_proposal: str, ike_proposal: str,
                       local_addr: str, remote_addr: str, local_id_base: str, remote_id_base: str) -> str:
    # Each experiment arm gets a UNIQUE IKE identity (id = <peer>-<arm>), not just a
    # unique connection/child name. This matters: strongSwan's responder selects the
    # candidate peer config primarily by local/remote ADDRESS and IDENTITY match, which
    # happens BEFORE child-SA proposal matching. Since every arm here shares the same
    # alice<->bob address pair, giving them identical IDs makes the responder's config
    # selection ambiguous — verified empirically: bob picked an arbitrary same-address
    # connection and then rejected the correct ESP proposal with NO_PROPOSAL_CHOSEN
    # because it was comparing against the WRONG arm's esp_proposals. Unique per-arm
    # IDs make selection deterministic. See testbed/NOTES.md "config-selection bug".
    local_id = f"{local_id_base}-{name}"
    remote_id = f"{remote_id_base}-{name}"
    if mode == "tunnel":
        ts_block = (
            f"                local_ts = {local_addr}/32\n"
            f"                remote_ts = {remote_addr}/32\n"
        )
    else:
        ts_block = ""  # transport mode protects host-to-host traffic; no explicit TS needed
    return f"""    {name} {{
        local_addrs  = {local_addr}
        remote_addrs = {remote_addr}
        local {{
            auth = psk
            id = {local_id}
        }}
        remote {{
            auth = psk
            id = {remote_id}
        }}
        version = 2
        proposals = {ike_proposal}
        children {{
            {name} {{
{ts_block}                mode = {mode}
                esp_proposals = {esp_proposal}
                start_action = none
                dpd_action = clear
                life_time = 3600
                rekey_time = 0
            }}
        }}
    }}
"""


def render_swanctl_conf(role: str, local_addr: str, remote_addr: str,
                         local_id: str, remote_id: str, matrix: dict) -> str:
    ike_proposal = matrix["ike_proposal_default"]
    conns = "".join(
        render_connection(arm["name"], arm["mode"], arm["esp_proposal"], ike_proposal,
                           local_addr, remote_addr, local_id, remote_id)
        for arm in matrix["arms"]
    )
    return HEADER.format(role=role) + f"""
connections {{
{conns}}}

secrets {{
    # Single wildcard PSK: IDs are now unique per experiment arm (see render_connection),
    # so we match by address/wildcard rather than by fixed alice/bob identities.
    ike-1 {{
        id-1 = %any
        id-2 = %any
        secret = "{matrix['psk']}"
    }}
}}
"""


def main() -> None:
    matrix = json.loads(MATRIX_PATH.read_text())

    alice_conf = render_swanctl_conf(
        role="alice (initiator, 10.10.1.10)",
        local_addr="10.10.1.10", remote_addr="10.10.2.10",
        local_id="alice", remote_id="bob", matrix=matrix,
    )
    bob_conf = render_swanctl_conf(
        role="bob (responder, 10.10.2.10)",
        local_addr="10.10.2.10", remote_addr="10.10.1.10",
        local_id="bob", remote_id="alice", matrix=matrix,
    )

    (CONFIGS_DIR / "alice" / "swanctl.conf").write_text(alice_conf)
    (CONFIGS_DIR / "bob" / "swanctl.conf").write_text(bob_conf)
    print(f"Wrote {len(matrix['arms'])} connection arms to alice/bob swanctl.conf")


if __name__ == "__main__":
    main()
