#!/usr/bin/env python3
"""Generate EXP-40 Libreswan IKEv1 config: testbed/configs/exp40/{ipsec.conf,ipsec.secrets,arms.json}

EXP-40 reads the negotiated suite of IKEv1 sessions (research/registers/EXPERIMENT-REGISTER.md, EXP-40).
One ipsec.conf serves both peers. Each arm has its own address pair (lsw-a 10.10.1.4k, lsw-b 10.10.2.4k).
Main mode identifies peers by IP address; aggressive mode (aggrmode=yes) by the @names below.
auto=ignore: conns are added by the harness AFTER the aliases exist.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
OUT = HERE.parent / "configs" / "exp40"
PSK_LINE = (HERE.parent / "configs" / "exp07" / "ipsec.secrets").read_text()      # the same lab-only throwaway PSK

# k: (arm, mode, ike)
ARMS = {
    1: ("e40-m-aes256-sha256-g14", "main", "aes256-sha2_256-modp2048"),
    2: ("e40-m-aes128-sha1-g5",    "main", "aes128-sha1-modp1536"),
    3: ("e40-m-3des-sha1-g5",      "main", "3des-sha1-modp1536"),
    4: ("e40-m-aes256-sha384-g15", "main", "aes256-sha2_384-modp3072"),
    5: ("e40-m-aes128-sha256-g19", "main", "aes128-sha2_256-dh19"),
    6: ("e40-a-aes256-sha256-g14", "aggressive", "aes256-sha2_256-modp2048"),
    7: ("e40-a-aes128-sha1-g5",    "aggressive", "aes128-sha1-modp1536"),
    8: ("e40-m-multi",             "main", "aes256-sha2_256-modp2048,aes128-sha1-modp1536"),
}


def a(k): return f"10.10.1.{40 + k}"
def b(k): return f"10.10.2.{40 + k}"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    conns = []
    for k, (name, mode, ike) in ARMS.items():
        ids = (f"\tleftid=@a-{name}\n\trightid=@b-{name}\n\taggrmode=yes\n" if mode == "aggressive" else "")
        conns.append(f"""conn {name}
\tleft={a(k)}
\tright={b(k)}
\tleftsubnet={a(k)}/32
\trightsubnet={b(k)}/32
{ids}\tauthby=secret
\tikev2=no
\tike={ike}
\tesp=aes_gcm256
\tpfs=no
\ttype=tunnel
\tikelifetime=8h
\tipsec-lifetime=8h
\trekey=no
\tauto=ignore
""")
    (OUT / "ipsec.conf").write_text(
        "# AUTO-GENERATED by testbed/scripts/gen_exp40_conf.py — do not hand-edit.\n"
        "config setup\n\tlogfile=/dev/stderr\n\tplutodebug=none\n\tikev1-policy=accept\n\n" + "\n".join(conns))
    # The responder (lsw-b) accepts only the SECOND of the multi arm's two offers, so the suite it selects differs
    # from the first offer: the only way to tell "what was selected" from "what was offered first".
    b_conns = [c.replace("ike=aes256-sha2_256-modp2048,aes128-sha1-modp1536", "ike=aes128-sha1-modp1536")
               if "conn e40-m-multi" in c else c for c in conns]
    (OUT / "ipsec.conf.b").write_text(
        "# AUTO-GENERATED by testbed/scripts/gen_exp40_conf.py — do not hand-edit. Responder variant (lsw-b).\n"
        "config setup\n\tlogfile=/dev/stderr\n\tplutodebug=none\n\tikev1-policy=accept\n\n" + "\n".join(b_conns))
    (OUT / "ipsec.secrets").write_text(PSK_LINE)
    (OUT / "arms.json").write_text(json.dumps(
        {n: {"k": k, "lsw_a": a(k), "lsw_b": b(k), "mode": m, "ike": i} for k, (n, m, i) in ARMS.items()}, indent=2))
    print(f"Wrote {len(ARMS)} arms to {OUT}")


if __name__ == "__main__":
    main()
