#!/usr/bin/env python3
"""Generate the EXP-50 Libreswan lab config: testbed/configs/exp50/{ipsec.conf,ipsec.conf.b,ipsec.secrets,arms.json}

For every Libreswan template of tunnelscope/remediate/vendors.py two arms are written: `-before` (the weak state in the template's
`example_before`) and `-after` (the same connection with the template's `example_after` lines applied as written: a value sets the line,
None removes it). Both ends read their own file (A: ipsec.conf, B: ipsec.conf.b); a rule whose weak state is on one end only has a
`b_before` override. Each arm has its own alias pair (10.10.1.<50+k> / 10.10.2.<50+k>) so arms never share XFRM policies.
The weak connection is built from the template's own text, so a template that does not work shows up as a failed `after` arm.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tunnelscope.remediate.vendors import TEMPLATES  # noqa: E402

OUT = ROOT / "testbed" / "configs" / "exp50"
PSK = "0sIhtestlab2026NoSecretpresharedkeydonotusehere"
BASE = {"authby": "secret", "keyexchange": "ikev2", "ike": "aes256-sha2_384-dh20", "esp": "aes_gcm256", "pfs": "no", "type": "tunnel",
        "ikelifetime": "8h", "ipsec-lifetime": "8h", "rekey": "no", "auto": "ignore"}
# the weak state on the OTHER end when it differs from the template's example_before (the rule's weakness is a mismatch of the two ends)
B_BEFORE = {"DST-PQ-DOWNGRADE": {"ike": "aes256-sha2_384-dh20"}}
# AH arms have no esp= line in the weak state
NO_ESP_WHEN = ("ah",)


def apply(conn: dict, edits: dict) -> dict:
    c = dict(conn)
    for k, v in edits.items():
        if v is None:
            c.pop(k, None)
        else:
            c[k] = v
    return c


def text(name, k, conn):
    head = {"left": f"10.10.1.{50 + k}", "right": f"10.10.2.{50 + k}", "leftid": f"@a-{name}", "rightid": f"@b-{name}",
            "leftsubnet": f"10.10.1.{50 + k}/32", "rightsubnet": f"10.10.2.{50 + k}/32"}
    lines = [f"conn {name}"] + [f"\t{key}={val}" for key, val in {**head, **conn}.items()]
    return "\n".join(lines) + "\n"


def main():
    arms, a_txt, b_txt = {}, [], []
    k = 0
    for rule, t in TEMPLATES["libreswan"].items():
        slug = rule.lower().replace("-", "")
        before = apply(BASE, t["example_before"])
        if t["example_before"].get("phase2") == "ah":
            before.pop("esp", None)
        after_a = apply(before, t["example_after"])
        before_b = apply(before, B_BEFORE.get(rule, {}))
        after_b = apply(before_b, t["example_after"])
        for state, ca, cb in (("before", before, before_b), ("after", after_a, after_b)):
            k += 1
            name = f"x50-{slug}-{state}"
            a_txt.append(text(name, k, ca))
            b_txt.append(text(name, k, cb))
            arms[name] = {"k": k, "rule": rule, "state": state, "a": f"10.10.1.{50 + k}", "b": f"10.10.2.{50 + k}", "conn_a": ca, "conn_b": cb}
    OUT.mkdir(parents=True, exist_ok=True)
    head = ("# AUTO-GENERATED by testbed/scripts/gen_exp50_conf.py — do not hand-edit.\nconfig setup\n\tlogfile=/dev/stderr\n\tplutodebug=none\n"
            "\tikev1-policy=accept\n\n")
    (OUT / "ipsec.conf").write_text(head + "\n".join(a_txt))
    (OUT / "ipsec.conf.b").write_text(head + "\n".join(b_txt))
    (OUT / "ipsec.secrets").write_text(f'%any %any : PSK "{PSK}"\n')
    (OUT / "arms.json").write_text(json.dumps(arms, indent=1, sort_keys=True) + "\n")
    print(f"{len(arms)} arms -> {OUT}")


if __name__ == "__main__":
    main()
