#!/usr/bin/env python3
"""Generate EXP-07 Libreswan config: testbed/configs/exp07/{ipsec.conf,ipsec.secrets,arms.json}

EXP-07 re-runs the structural experiments on a SECOND IPsec implementation
(Libreswan 5.4) to see which findings are protocol facts and which are
strongSwan behaviour: EXP-01 cipher sieve, EXP-02 AES-128/256 negative
control, EXP-03 PFS rekey gap, EXP-04 PQ signals.

One ipsec.conf serves both peers: pluto works out which side is local by
matching its own interface addresses. Each arm has its own alias pair
(lsw-a 10.10.1.3k, lsw-b 10.10.2.3k), so arms can't share XFRM policies.
auto=ignore: conns are added by the harness AFTER the aliases exist.

Pre-registration: research/registers/EXPERIMENT-REGISTER.md ("EXP-07 — PRE-REGISTRATION").
"""
import json
import pathlib

OUT = pathlib.Path(__file__).parent.parent / "configs" / "exp07"
PSK = "0sIhtestlab2026SIH26160presharedkeydonotusehere"
IKE = "aes256-sha2_256-modp2048"

# k: (arm, esp, pfs, ike, extra, feeds)
ARMS = {
    1: ("e7-gcm128",     "aes_gcm128",           "no",  IKE, [], "EXP-01, EXP-02"),
    2: ("e7-gcm256",     "aes_gcm256",           "no",  IKE, [], "EXP-01, EXP-02"),
    3: ("e7-cbc128",     "aes128-sha2_256",      "no",  IKE, [], "EXP-01, EXP-02"),
    4: ("e7-cbc256",     "aes256-sha2_256",      "no",  IKE, [], "EXP-01, EXP-02"),
    5: ("e7-chacha",     "chacha20_poly1305",    "no",  IKE, [], "EXP-01"),
    6: ("e7-ctr128",     "aes_ctr128-sha2_256",  "no",  IKE, [], "EXP-01"),
    7: ("e7-pfs-off",    "aes_gcm256",           "no",  IKE, [], "EXP-03"),
    8: ("e7-pfs-on",     "aes_gcm256",           "yes", IKE, [], "EXP-03"),
    9: ("e7-classical",  "aes_gcm256",           "no",  IKE, ["intermediate=yes", "fragmentation=yes"], "EXP-04 baseline"),
    10: ("e7-pq",        "aes_gcm256",           "no",  IKE + ";addke1=ml_kem_768", ["intermediate=yes", "fragmentation=yes"], "EXP-04 PQ"),
}


def a(k): return f"10.10.1.{30 + k}"
def b(k): return f"10.10.2.{30 + k}"


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    conns = []
    for k, (name, esp, pfs, ike, extra, feeds) in ARMS.items():
        extra_lines = "".join(f"\t{e}\n" for e in extra)
        conns.append(f"""# {feeds}
conn {name}
\tleft={a(k)}
\tright={b(k)}
\tleftid=@a-{name}
\trightid=@b-{name}
\tleftsubnet={a(k)}/32
\trightsubnet={b(k)}/32
\tauthby=secret
\tkeyexchange=ikev2
\tike={ike}
\tesp={esp}
\tpfs={pfs}
\ttype=tunnel
\tikelifetime=8h
\tipsec-lifetime=8h
\trekey=no
{extra_lines}\tauto=ignore
""")
    (OUT / "ipsec.conf").write_text(
        "# AUTO-GENERATED by testbed/scripts/gen_exp07_conf.py — do not hand-edit.\n"
        "config setup\n\tlogfile=/dev/stderr\n\tplutodebug=none\n\n" + "\n".join(conns))
    (OUT / "ipsec.secrets").write_text(f'%any %any : PSK "{PSK}"\n')
    (OUT / "arms.json").write_text(json.dumps(
        {n: {"k": k, "lsw_a": a(k), "lsw_b": b(k), "esp": e, "pfs": p, "ike": i, "feeds": f}
         for k, (n, e, p, i, _, f) in ARMS.items()}, indent=2))
    print(f"Wrote {len(ARMS)} arms to {OUT}")


if __name__ == "__main__":
    main()
