#!/usr/bin/env python3
"""Generate EXP-05 swanctl configs: testbed/configs/exp05/{alice,bob}.conf

EXP-05 measures how much a passive (T0) observer can learn about the traffic
class inside an ESP tunnel, and how much TFC padding / IP-TFS reduces it.
Runs on the PQ pair (strongSwan 6.1.0): kernel 7.0 supports AGGFRAG (IP-TFS),
and keeping one implementation across all arms removes it as a confounder.

Each arm gets its own alias pair (alice-pq 10.10.1.20j, bob-pq 10.10.2.20j),
as in EXP-06 round 2, so arms can't share XFRM policies.

Pre-registration: research/registers/EXPERIMENT-REGISTER.md ("EXP-05 — PRE-REGISTRATION").
"""
import json
import pathlib

OUT = pathlib.Path(__file__).parent.parent / "configs" / "exp05"
PSK = "0sIhtestlab2026SIH26160presharedkeydonotusehere"

# j: (name, child-level extra lines, description)
ARMS = {
    0: ("base",  [],                        "tunnel mode, no TFC padding (strongSwan default tfc_padding=0)"),
    1: ("tfc",   ["tfc_padding = mtu"],     "tunnel mode, every ESP packet padded to the path MTU (RFC 4303 sec 2.7)"),
    2: ("iptfs", [],                        "AGGFRAG / IP-TFS mode (RFC 9347); charon.iptfs.packet_size set in strongswan.conf"),
    3: ("mux",   [],                        "tunnel mode, no padding; carries TWO concurrent traffic classes (G-12 multiplexing)"),
}


def addr(side, j):
    return f"10.10.{1 if side == 'alice' else 2}.{200 + j}"


def render(side):
    me, peer = ("alice", "bob") if side == "alice" else ("bob", "alice")
    conns, secrets = [], []
    for j, (name, extra, desc) in ARMS.items():
        mode = "iptfs" if name == "iptfs" else "tunnel"
        extra_lines = "".join(f"                {e}\n" for e in extra)
        conns.append(f"""    # {desc}
    e5-{name} {{
        local_addrs  = {addr(me, j)}
        remote_addrs = {addr(peer, j)}
        local {{
            auth = psk
            id = {me[0]}-e5-{name}
        }}
        remote {{
            auth = psk
            id = {peer[0]}-e5-{name}
        }}
        version = 2
        proposals = aes256-sha256-modp2048
        children {{
            e5-{name} {{
                local_ts = {addr(me, j)}/32
                remote_ts = {addr(peer, j)}/32
                mode = {mode}
                esp_proposals = aes256gcm16
{extra_lines}                start_action = none
                dpd_action = clear
                life_time = 7200
                rekey_time = 0
            }}
        }}
    }}
""")
        secrets.append(f"""    ike-e5-{name} {{
        id-1 = {me[0]}-e5-{name}
        id-2 = {peer[0]}-e5-{name}
        secret = "{PSK}"
    }}
""")
    return (f"# AUTO-GENERATED by testbed/scripts/gen_exp05_conf.py — EXP-05 ({side}). Do not hand-edit.\n"
            "connections {\n" + "".join(conns) + "}\n\nsecrets {\n" + "".join(secrets) + "}\n")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for side in ("alice", "bob"):
        (OUT / f"{side}.conf").write_text(render(side))
    (OUT / "arms.json").write_text(json.dumps(
        {f"e5-{n}": {"alice": addr("alice", j), "bob": addr("bob", j), "description": d}
         for j, (n, _, d) in ARMS.items()}, indent=2))
    print(f"Wrote {len(ARMS)} arms to {OUT}")


if __name__ == "__main__":
    main()
