#!/usr/bin/env python3
"""Generate EXP-15 swanctl configs: testbed/configs/exp15/{alice,bob}.conf

Pre-registration: experiments/exp15-traffic-classes-suites-ah/PREREG.md.
PQ pair (strongSwan 6.1.0). Each arm has its own alias pair
(alice-pq 10.10.1.{210+j}, bob-pq 10.10.2.{210+j}) so arms never share
XFRM policies.
"""
import json
import pathlib

OUT = pathlib.Path(__file__).parent.parent / "configs" / "exp15"
PSK = "0sIhtestlab2026SIH26160presharedkeydonotusehere"
GCM = "aes256-sha256-modp2048"

# j: name, IKE proposals, child protocol ("esp"|"ah"), child proposals, mode, extra child lines, description
ARMS = {
    # Part A: traffic classes
    0: ("t-tun", GCM, "esp", "aes256gcm16", "tunnel", [], "traffic: tunnel, AES-GCM-256"),
    1: ("t-tfc", GCM, "esp", "aes256gcm16", "tunnel", ["tfc_padding = mtu"], "traffic: tunnel, TFC padding to MTU"),
    2: ("t-tra", GCM, "esp", "aes256gcm16", "transport", [], "traffic: transport, AES-GCM-256"),
    3: ("t-mux", GCM, "esp", "aes256gcm16", "tunnel", [], "traffic: tunnel, two classes at once"),
    4: ("t-cbc", GCM, "esp", "aes128-sha256", "tunnel", [], "traffic: tunnel, AES-CBC-128 + HMAC-SHA-256"),
    # Part B: IKE / DH suite variety
    10: ("s-modp1024", "aes128-sha1-modp1024", "esp", "aes128-sha1", "tunnel", [], "suite: MODP-1024, AES-128, SHA-1 (weak)"),
    11: ("s-modp1536", "aes128-sha256-modp1536", "esp", "aes128-sha256", "tunnel", [], "suite: MODP-1536 (SHOULD NOT)"),
    12: ("s-modp3072", "aes256-sha256-modp3072", "esp", "aes256-sha256-modp3072", "tunnel", [], "suite: MODP-3072, PFS"),
    13: ("s-modp4096", "aes256-sha384-modp4096", "esp", "aes256gcm16-modp4096", "tunnel", [], "suite: MODP-4096, SHA-384, PFS"),
    14: ("s-ecp256", "aes128gcm16-prfsha256-ecp256", "esp", "aes128gcm16", "tunnel", [], "suite: ECP-256, AES-GCM-128"),
    15: ("s-ecp384", "aes256gcm16-prfsha384-ecp384", "esp", "aes256gcm16-ecp384", "tunnel", [], "suite: ECP-384, AES-GCM-256, PFS"),
    16: ("s-x25519", "aes256-sha256-x25519", "esp", "chacha20poly1305", "tunnel", [], "suite: Curve25519, ChaCha20-Poly1305 ESP"),
    17: ("s-3des", "3des-sha1-modp1024", "esp", "3des-sha1", "tunnel", [], "suite: 3DES, SHA-1, MODP-1024 (legacy)"),
    18: ("s-mlkem", "aes256-sha256-x25519-ke1_mlkem768", "esp", "aes256gcm16", "tunnel", [], "suite: Curve25519 + ML-KEM-768 hybrid"),
    # Part C: AH
    20: ("a-tun-sha256", GCM, "ah", "sha256", "tunnel", [], "AH tunnel, HMAC-SHA-256-128"),
    21: ("a-tra-sha256", GCM, "ah", "sha256", "transport", [], "AH transport, HMAC-SHA-256-128"),
    22: ("a-tra-sha1", GCM, "ah", "sha1", "transport", [], "AH transport, HMAC-SHA-1-96"),
    23: ("a-tun-sha384", GCM, "ah", "sha384", "tunnel", [], "AH tunnel, HMAC-SHA-384-192"),
    24: ("a-tra-sha512", GCM, "ah", "sha512", "transport", [], "AH transport, HMAC-SHA-512-256"),
}


def addr(side, j):
    return f"10.10.{1 if side == 'alice' else 2}.{210 + j}"


def render(side):
    me, peer = ("alice", "bob") if side == "alice" else ("bob", "alice")
    conns, secrets = [], []
    for j, (name, ike, proto, child, mode, extra, desc) in ARMS.items():
        lines = "".join(f"                {e}\n" for e in extra)
        conns.append(f"""    # {desc}
    {name} {{
        local_addrs  = {addr(me, j)}
        remote_addrs = {addr(peer, j)}
        local {{
            auth = psk
            id = {me[0]}-{name}
        }}
        remote {{
            auth = psk
            id = {peer[0]}-{name}
        }}
        version = 2
        proposals = {ike}
        children {{
            {name} {{
                local_ts = {addr(me, j)}/32
                remote_ts = {addr(peer, j)}/32
                mode = {mode}
                {proto}_proposals = {child}
{lines}                start_action = none
                dpd_action = clear
                life_time = 7200
                rekey_time = 0
            }}
        }}
    }}
""")
        secrets.append(f"""    ike-{name} {{
        id-1 = {me[0]}-{name}
        id-2 = {peer[0]}-{name}
        secret = "{PSK}"
    }}
""")
    return ("# AUTO-GENERATED by testbed/scripts/gen_exp15_conf.py (EXP-15). Do not hand-edit.\n"
            "connections {\n" + "".join(conns) + "}\n\nsecrets {\n" + "".join(secrets) + "}\n")


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    for side in ("alice", "bob"):
        (OUT / f"{side}.conf").write_text(render(side))
    (OUT / "arms.json").write_text(json.dumps(
        {name: {"j": j, "ike": ike, "proto": proto, "child": child, "mode": mode, "extra": extra, "desc": desc}
         for j, (name, ike, proto, child, mode, extra, desc) in ARMS.items()}, indent=2))
    print(f"wrote {OUT}/alice.conf, bob.conf, arms.json ({len(ARMS)} arms)")
