"""EXP-27: RFC 8784 PPK arms on the strongSwan 6.1.0 lab (alice-pq -> bob-pq), captured at the router.

Per arm: write both peers' swanctl files to testbed/configs/exp27/, load ONLY that arm on both charons
(`swanctl --load-all --file`), capture on the router, initiate, ping, save both charons' logs and SA
lists as ground truth. At the end the lab's standing configs are reloaded.

  .venv/bin/python testbed/scripts/run_exp27_ppk.py [K0 K1 ...]
"""
import json
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

TB = Path(__file__).resolve().parents[1]
CONF, CAP = TB / "configs" / "exp27", TB / "captures" / "exp27"
PSK = "0sIhtestlab2026SIH26160presharedkeydonotusehere"         # lab-only throwaway (as the rest of testbed/)
PPK = {"ppk27": "0x" + "a7" * 32, "other27": "0x" + "5c" * 32}   # lab-only throwaway PPKs
# arm: (initiator ppk_id, initiator required, responder ppk_id, responder required)
ARMS = {"K0": (None, False, None, False), "K1": ("ppk27", False, "ppk27", False),
        "K2": ("ppk27", True, "ppk27", True), "K3": ("ppk27", False, None, False),
        "K4": ("ppk27", False, "other27", False),
        # K5, added after K4 (declared deviation in RESULT.md): the responder's matching connection has no
        # PPK, but a decoy connection of its own does, so it still answers USE_PPK -> silent fallback.
        "K5": ("ppk27", False, None, False)}
DECOY = """    decoy-k5 {{
        local_addrs  = 10.10.2.20
        remote_addrs = 10.10.1.20
        local {{
            auth = psk
            id = bob-decoy-k5
        }}
        remote {{
            auth = psk
            id = someone-else-k5
        }}
        version = 2
        proposals = aes256-sha256-modp2048
        ppk_id = other27
        ppk_required = no
    }}
"""


def conf(arm, me, peer, my_ip, peer_ip, my_ts, peer_ts, ppk_id, required):
    name = f"ppk-{arm.lower()}"
    ppk = f"        ppk_id = {ppk_id}\n        ppk_required = {'yes' if required else 'no'}\n" if ppk_id else ""
    secrets = f'    ppk-{ppk_id} {{\n        secret = {PPK[ppk_id]}\n        id = {ppk_id}\n    }}\n' if ppk_id else ""
    decoy = DECOY.format() if (arm == "K5" and me == "bob") else ""
    secrets = secrets or (f'    ppk-other27 {{\n        secret = {PPK["other27"]}\n        id = other27\n    }}\n' if decoy else "")
    return f"""# EXP-27 arm {arm} ({me}); generated by testbed/scripts/run_exp27_ppk.py
connections {{
    {name} {{
        local_addrs  = {my_ip}
        remote_addrs = {peer_ip}
        local {{
            auth = psk
            id = {me}-{name}
        }}
        remote {{
            auth = psk
            id = {peer}-{name}
        }}
        version = 2
        proposals = aes256-sha256-modp2048
{ppk}        children {{
            {name} {{
                local_ts = {my_ts}
                remote_ts = {peer_ts}
                mode = tunnel
                esp_proposals = aes256gcm16
                start_action = none
            }}
        }}
    }}
{decoy}}}
secrets {{
    ike-1 {{
        id-1 = %any
        id-2 = %any
        secret = "{PSK}"
    }}
{secrets}}}
"""


def sh(*cmd, check=True):
    return subprocess.run(cmd, capture_output=True, text=True, check=check).stdout


def load(container, path):
    sh("docker", "cp", str(path), f"{container}:/tmp/exp27.conf")
    return sh("docker", "exec", container, "swanctl", "--load-all", "--file", "/tmp/exp27.conf")


def run(arm):
    i_id, i_req, r_id, r_req = ARMS[arm]
    CONF.mkdir(parents=True, exist_ok=True)
    CAP.mkdir(parents=True, exist_ok=True)
    a = CONF / f"alice-{arm.lower()}.conf"
    b = CONF / f"bob-{arm.lower()}.conf"
    a.write_text(conf(arm, "alice", "bob", "10.10.1.20", "10.10.2.20", "10.10.1.20/32", "10.10.2.20/32", i_id, i_req))
    b.write_text(conf(arm, "bob", "alice", "10.10.2.20", "10.10.1.20", "10.10.2.20/32", "10.10.1.20/32", r_id, r_req))
    for c in ("sih26-alice-pq", "sih26-bob-pq"):
        sh("docker", "exec", c, "swanctl", "--terminate", "--ike", f"ppk-{arm.lower()}", check=False)
    load("sih26-bob-pq", b)
    load("sih26-alice-pq", a)
    pcap = f"/captures/exp27/ppk-{arm.lower()}.pcap"
    sh("docker", "exec", "sih26-router", "mkdir", "-p", "/captures/exp27")
    sh("docker", "exec", "-d", "sih26-router", "bash", "-c",
       f"rm -f {pcap}; tcpdump -i eth0 -w {pcap} 'ip proto 50 or udp port 500 or udp port 4500'")
    time.sleep(1)
    since = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    init = sh("docker", "exec", "sih26-alice-pq", "swanctl", "--initiate", "--child", f"ppk-{arm.lower()}", check=False)
    for s in (0, 64, 256, 512, 1024, 1400):
        sh("docker", "exec", "sih26-alice-pq", "ping", "-c", "3", "-i", "0.1", "-s", str(s), "-W", "1", "10.10.2.20", check=False)
    time.sleep(1)
    sh("docker", "exec", "sih26-router", "pkill", "-INT", "tcpdump", check=False)
    time.sleep(1)
    logs = {c: subprocess.run(["docker", "logs", "--since", since, c], capture_output=True, text=True)
            for c in ("sih26-alice-pq", "sih26-bob-pq")}
    gt = {"experiment": "EXP-27", "arm": arm, "capture": f"ppk-{arm.lower()}.pcap",
          "config": {"initiator_ppk_id": i_id, "initiator_ppk_required": i_req,
                     "responder_ppk_id": r_id, "responder_ppk_required": r_req},
          "initiate_output": init,
          "alice_list_sas": sh("docker", "exec", "sih26-alice-pq", "swanctl", "--list-sas", check=False),
          "bob_list_sas": sh("docker", "exec", "sih26-bob-pq", "swanctl", "--list-sas", check=False),
          "alice_log": logs["sih26-alice-pq"].stdout + logs["sih26-alice-pq"].stderr,
          "bob_log": logs["sih26-bob-pq"].stdout + logs["sih26-bob-pq"].stderr,
          "ground_truth_source": "strongSwan 6.1.0 charon logs + swanctl --list-sas on both peers (T2)"}
    (CAP / f"ppk-{arm.lower()}.groundtruth.json").write_text(json.dumps(gt, indent=1) + "\n")
    ppk_lines = [ln for ln in gt["alice_log"].splitlines() + gt["bob_log"].splitlines() if "PPK" in ln]
    print(f"== {arm}: established={'established' in init} | " + " || ".join(ppk_lines[:4]))


if __name__ == "__main__":
    try:
        for arm in (sys.argv[1:] or list(ARMS)):
            run(arm)
    finally:
        for c in ("sih26-alice-pq", "sih26-bob-pq"):
            sh("docker", "exec", c, "swanctl", "--load-all", check=False)   # back to the standing config
