charon {
    load_modular = yes
    plugins {
        include strongswan.d/charon/*.conf
    }
    filelog {
        stderr {
            default = 2
            ike = 3
            enc = 2
            knl = 2
        }
    }
    # vici socket for swanctl
    vici {
        socket = unix:///var/run/charon.vici
    }
}
include strongswan.d/*.conf
