connections {
    rekey-cadence {
        local_addrs  = 10.10.1.10
        remote_addrs = 10.10.2.10
        local {
            auth = psk
            id = alice-rekey-cadence
        }
        remote {
            auth = psk
            id = bob-rekey-cadence
        }
        version = 2
        proposals = aes256-sha256-modp2048
        children {
            rekey-cadence {
                local_ts = 10.10.1.10/32
                remote_ts = 10.10.2.10/32
                mode = tunnel
                esp_proposals = aes256gcm16
                start_action = none
                dpd_action = clear
                life_time = 300
                rekey_time = 20
            }
        }
    }
}
