"""T-123 / EXP-50: fix templates for devices that are not strongSwan.

The strongSwan plans in `plan.py` are untouched (and so is their safe-apply pipeline). This module adds hand-written
advice in the vocabulary of two other vendors, Libreswan and MikroTik RouterOS. Nothing here is executed or sent anywhere,
and nothing generated by a model: each template is a table row that a test checks against the vendor's documentation, and
each carries how far it was verified:

  "lab"              the template's lines were applied to a running device by the EXP-50 harness, the tunnel was re-established and
                     TunnelScope reported the rule fixed (and no rule that passed before failed after).
  "lab-device-state" applied on a running device and the device's own report shows the change; TunnelScope's wire verdict could not
                     confirm it (see the table below), or no tunnel was negotiated.
  "docs-only"        every setting name and value is in the vendor's documentation (checked by a test); not run on a device.

A rule with no honest template for a vendor has `template: None` and a `reason`. A fixed-version claim is never made here
(that is T-161's job); patch rules point to the vendor's own advisories.
"""
from __future__ import annotations

SUPPORTED = ("strongswan", "libreswan", "mikrotik")
VENDOR_LABEL = {"libreswan": "Libreswan", "mikrotik": "MikroTik RouterOS"}
SOURCES = {
    "libreswan": "libreswan.org/man/ipsec.conf.5.html (ipsec.conf(5), page dated 2025-03-01) and the Libreswan 5.4 lab image (EXP-50)",
    "mikrotik": "help.mikrotik.com/docs/spaces/ROS/pages/11993097/IPsec (RouterOS IPsec, retrieved 2026-10-05)",
}
PATCH_RULES = ("CVE-WATCH-KE-MALFORMED", "CVE-WATCH-INFO-BEFORE-AUTH", "CVE-WATCH-INIT-PAYLOADS", "CVE-2026-78135", "RFC4303-SEQ")
_PATCH_REASON = ("software patch or investigation, not a configuration change; see the vendor's own security advisories "
                 "(no fixed version is claimed here)")

LSW_RELOAD = "ipsec replace <conn>"          # `ipsec auto` is deprecated in Libreswan 5.4; `ipsec replace` ran on the lab pair (EXP-50)
LSW_CONF = "the connection's section in /etc/ipsec.conf, on both ends"


def _lsw(change, why, before, after, verification="docs-only", also=None, verify=None):
    """One Libreswan template. `before`/`after` are the weak and fixed `key=value` lines of the connection; the lab harness builds the
    weak connection from `before` and applies `after` as written."""
    lines = [f"{k}={v}" for k, v in after.items() if v is not None]
    gone = [k for k, v in after.items() if v is None]                  # a None value means: remove that line
    return {"change": change, "why": why, "example_before": dict(before), "example_after": dict(after),
            "commands": [f"in {LSW_CONF}, set: " + "  ".join(lines)] + ([f"remove the line(s): {', '.join(gone)}"] if gone else [])
                        + ([also] if also else []) + [LSW_RELOAD],
            "config_diff": "\n".join([f"- {k}={v}" for k, v in before.items()] + [f"+ {k}={v}" for k, v in after.items() if v is not None]
                                      + [f"- {k}" for k in gone]),
            "verify": verify or "ipsec status   (the established connection lists the new algorithms)",
            "verification": verification}


def _ros(change, why, edits, verification="docs-only"):
    """One RouterOS template. `edits`: list of (menu, label, {setting: value}); `<label>` is the item's name on the device. A label that
    contains `=` is a finder expression as it is (policies have no name: `ipsec-protocols=ah`)."""
    cmds, diff = [], []
    for menu, label, settings in edits:
        find = label if "=" in label else f"name=<{label}>"
        cmds.append(f"{menu} set [ find {find} ] " + " ".join(f"{k}={v}" for k, v in settings.items()))
        diff += [f"+ {menu} [{find}] {k}={v}" for k, v in settings.items()]
    verify = "; ".join(f"{m} print detail where " + (f"{next(iter(st))}={st[next(iter(st))]}" if "=" in lb else f"name=<{lb}>") for m, lb, st in edits)
    return {"change": change, "why": why, "commands": cmds, "config_diff": "\n".join(diff), "verify": verify,
            "verification": verification, "edits": [{"menu": m, "label": lb, "set": dict(s)} for m, lb, s in edits]}


PROFILE, PEER, PROPOSAL, POLICY = "/ip ipsec profile", "/ip ipsec peer", "/ip ipsec proposal", "/ip ipsec policy"

TEMPLATES: dict[str, dict[str, dict]] = {
    "libreswan": {
        "V-207205": _lsw("Move IKEv1 to IKEv2", "keyexchange=ikev2 replaces the older ikev2=yes|no keyword (ipsec.conf(5))",
                         {"keyexchange": "ikev1"}, {"keyexchange": "ikev2"},
                         also="to refuse IKEv1 packets for the whole daemon, in `config setup` set ikev1-policy=drop (the default; ipsec.conf(5))"),
        "V-207193": _lsw("Raise the DH group", "replace only the group element of the ike= proposal with dh20 (ECP-384) or dh16 (MODP-4096)",
                         {"ike": "aes256-sha2_384-dh14"}, {"ike": "aes256-sha2_384-dh20"}),
        "V-207223": _lsw("Raise integrity to SHA-384+", "replace only the hash element of the ike= proposal with sha2_384 or sha2_512",
                         {"ike": "aes256-sha2_256-dh20"}, {"ike": "aes256-sha2_384-dh20"}),
        "RFC8247-DH-MUST": _lsw("Drop a forbidden DH group that was picked", "replace the forbidden group (dh1, dh2, dh5, dh22-24) in the ike= proposal",
                                {"ike": "aes256-sha2_384-dh5"}, {"ike": "aes256-sha2_384-dh20"}),
        "RFC8247-DH-OFFER": _lsw("Drop a forbidden DH group still offered", "remove the proposal that names the forbidden group from the ike= list, on the end that offers it",
                                 {"ike": "aes256-sha2_384-dh20,aes256-sha2_384-dh5"}, {"ike": "aes256-sha2_384-dh20"}),
        "RFC8247-ENCR": _lsw("Handshake cipher to AES", "replace the non-AES cipher element of the ike= proposal with aes256 (or aes_gcm256)",
                             {"ike": "3des-sha2_384-dh20"}, {"ike": "aes256-sha2_384-dh20"}),
        "DST-PQ-KE": _lsw("Add hybrid PQ key exchange", "Libreswan 5.4: a second key exchange is added with addke1= inside the ike= proposal (RFC 9370), with IKE_INTERMEDIATE and fragmentation on",
                          {"ike": "aes256-sha2_384-dh20"},
                          {"ike": "aes256-sha2_384-dh20;addke1=ml_kem_768", "intermediate": "yes", "fragmentation": "yes"}),
        "DST-PQ-DOWNGRADE": _lsw("Stop allowing classical-only fallback", "remove the proposal that has no addke1= from the ike= list on every end, so a peer without ML-KEM cannot be negotiated down to classical",
                                 {"ike": "aes256-sha2_384-dh20;addke1=ml_kem_768,aes256-sha2_384-dh20", "intermediate": "yes", "fragmentation": "yes"},
                                 {"ike": "aes256-sha2_384-dh20;addke1=ml_kem_768", "intermediate": "yes", "fragmentation": "yes"}),
        "RFC4301-CONFIDENTIALITY": _lsw("AH to ESP", "phase2=esp (the default) with an esp= proposal replaces phase2=ah with ah=",
                                        {"phase2": "ah", "ah": "sha2_256"}, {"phase2": "esp", "esp": "aes_gcm256", "ah": None}),
        "RFC8221-AH-INTEG": _lsw("AH integrity off MD5", "replace the ah= algorithm with sha2_256 (or sha2_512)",
                                 {"phase2": "ah", "ah": "md5"}, {"ah": "sha2_256"}),
        "RFC8221-AH-LEGACY": _lsw("AH integrity off legacy 96-bit", "replace the ah= algorithm with sha2_256 (or sha2_512)",
                                  {"phase2": "ah", "ah": "sha1"}, {"ah": "sha2_256"}),
        "RFC8221-ESP-3DES": _lsw("ESP cipher off 3DES", "replace the 3des element of the esp= proposal with aes_gcm256 (or aes256)",
                                 {"esp": "3des-sha1"}, {"esp": "aes_gcm256"}),
    },
    "mikrotik": {
        "V-207205": _ros("Move IKEv1 to IKEv2", "exchange-mode=ike2 turns on IKEv2 for the peer (RouterOS IPsec, peer table)",
                         [(PEER, "peer", {"exchange-mode": "ike2"})]),
        "V-207193": _ros("Raise the DH group", "profile dh-group accepts ecp384 and modp4096",
                         [(PROFILE, "profile", {"dh-group": "ecp384"})]),
        "V-207223": _ros("Raise integrity to SHA-512 (or SHA-384)", "the RouterOS page lists hash-algorithm as md5, sha1, sha256, sha512; RouterOS 7.24.4 also accepted sha384 "
                         "on the lab device (EXP-26 negotiated it, EXP-50 set it) although the page omits it, so sha384 is a valid alternative for 'SHA-384 or higher'",
                         [(PROFILE, "profile", {"hash-algorithm": "sha512"})]),
        "RFC8247-DH-MUST": _ros("Drop a forbidden DH group that was picked", "the profile dh-group list must not contain modp768, modp1024 or modp1536 (groups 1, 2, 5); RouterOS has no groups 22-24",
                                [(PROFILE, "profile", {"dh-group": "ecp384"})]),
        "RFC8247-DH-OFFER": _ros("Drop a forbidden DH group still offered", "do this on the router that offers it: its profile dh-group list is what it offers in IKE_SA_INIT",
                                 [(PROFILE, "profile", {"dh-group": "ecp384"})]),
        "RFC8247-ENCR": _ros("Handshake cipher to AES", "profile enc-algorithm accepts aes-256 (the profile's list is the IKE cipher offer)",
                             [(PROFILE, "profile", {"enc-algorithm": "aes-256"})]),
        "RFC4301-CONFIDENTIALITY": _ros("AH to ESP", "policy ipsec-protocols accepts ah or esp (default esp)",
                                        [(POLICY, "ipsec-protocols=ah", {"ipsec-protocols": "esp"})]),
        "RFC8221-AH-INTEG": _ros("AH integrity off MD5", "proposal auth-algorithms accepts md5, null, sha1, sha256, sha512",
                                 [(PROPOSAL, "proposal", {"auth-algorithms": "sha256"})]),
        "RFC8221-AH-LEGACY": _ros("AH integrity off legacy 96-bit", "proposal auth-algorithms accepts sha256 and sha512",
                                  [(PROPOSAL, "proposal", {"auth-algorithms": "sha256"})]),
        "RFC8221-ESP-3DES": _ros("ESP cipher off 3DES", "AES-GCM already authenticates, so RouterOS refuses it next to any auth-algorithms value, including the documented "
                                 "`null` (device answer, EXP-50: 'AEAD already provides authentication'); an EMPTY auth-algorithms is what it accepts. Alternative "
                                 "without GCM: enc-algorithms=aes-256-cbc with auth-algorithms=sha256",
                                 [(PROPOSAL, "proposal", {"enc-algorithms": "aes-256-gcm", "auth-algorithms": '""'})]),
    },
}
# EXP-50 lab result for the Libreswan 5.4 pair (experiments/exp50-vendor-fixes/results/summary-libreswan.json; a test ties this table to that file).
#   lab              TunnelScope saw the weak state FAIL on the wire, the template's lines were applied on the pair, the tunnel came back up and
#                    TunnelScope reported the rule PASS with no other rule going PASS -> FAIL.
#   lab-device-state the wire cannot show the weak state (AH HMAC-MD5-96 and HMAC-SHA1-96 look alike; the ESP 3DES family stays UNKNOWN), so the
#                    check was Libreswan's own algorithm report: weak algorithm before, strong one after, tunnel up.
_LIBRESWAN_LAB = {"V-207205": "lab", "V-207193": "lab", "V-207223": "lab", "RFC8247-DH-MUST": "lab", "RFC8247-DH-OFFER": "lab", "RFC8247-ENCR": "lab",
                  "DST-PQ-KE": "lab", "DST-PQ-DOWNGRADE": "lab", "RFC4301-CONFIDENTIALITY": "lab", "RFC8221-AH-LEGACY": "lab",
                  "RFC8221-AH-INTEG": "lab-device-state", "RFC8221-ESP-3DES": "lab-device-state"}
for _rule, _label in _LIBRESWAN_LAB.items():
    TEMPLATES["libreswan"][_rule]["verification"] = _label

_ROS_NO_PQ = ("the RouterOS IPsec documentation (retrieved 2026-10-05) lists no post-quantum key exchange: dh-group and pfs-group accept "
              "classical groups only (modp and ecp)")
NO_TEMPLATE: dict[str, dict[str, str]] = {"libreswan": {}, "mikrotik": {"DST-PQ-KE": _ROS_NO_PQ, "DST-PQ-DOWNGRADE": _ROS_NO_PQ}}


def vendor_plan(rule_id: str, vendor: str, observed=None, detailed: bool = False) -> dict | None:
    """The plan for `rule_id` on `vendor`, or None when TunnelScope has no plan for the rule at all."""
    from .plan import REMEDIATION
    base = REMEDIATION.get(rule_id)
    if not base:
        return None
    t = TEMPLATES[vendor].get(rule_id)
    reason = None
    if t is None:
        reason = _PATCH_REASON if rule_id in PATCH_RULES else NO_TEMPLATE[vendor].get(rule_id, "no template written for this rule on this vendor yet")
    res = {"rule_id": str(rule_id), "vendor": vendor, "vendor_label": VENDOR_LABEL[vendor], "observed": observed,
           "template": t is not None, "auto_applicable": False, "automated_fix_available": False,
           "change": t["change"] if t else base["change"], "commands": list(t["commands"]) if t else [],
           "verification": t["verification"] if t else None, "source": SOURCES[vendor]}
    if t is None:
        res["reason"] = reason
    if detailed:
        res["config_diff"] = t["config_diff"] if t else ""
        res["config_diff_is_example"] = True
        res["verify"] = t["verify"] if t else ""
        res["why"] = t["why"] if t else ""
        res["problem_analysis"] = base.get("problem_analysis", "")
        res["cryptographic_risk"] = base.get("cryptographic_risk", "")
        res["scope"] = ("Advice only: nothing is applied by TunnelScope on this vendor. The dry-run, snapshot and rollback pipeline "
                        "exists for the strongSwan lab only.")
    return res
