"""The strongSwan keyword vocabulary (T-100): which algorithm keywords the lab's strongSwan
accepts, what kind of algorithm each one is, and what TunnelScope reports on the wire for it.

The data file `strongswan_keywords.json` is generated by `testbed/scripts/probe_keywords.sh`
from the lab images and the EXP-15 captures; nothing in it is typed by hand. This module only
reads it. A keyword that is not in the file is treated as unknown, and an algorithm whose wire
value was never observed has no evidence value: callers must refuse rather than guess.
"""
from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

VOCAB_PATH = Path(__file__).with_name("strongswan_keywords.json")
TOKEN_SHAPE = re.compile(r"^[a-z0-9_]+$")
# Which proposal context each config line belongs to.
CONTEXT_OF_LINE = {"proposals": "ike", "esp_proposals": "esp", "ah_proposals": "ah"}


@lru_cache(maxsize=4)
def load_vocab(path: str | None = None) -> dict[str, Any]:
    return json.loads(Path(path or VOCAB_PATH).read_text())


def image_ids(vocab: dict[str, Any] | None = None) -> set[str]:
    return set((vocab or load_vocab())["images"].values())


def check_image(image_id: str | None, vocab: dict[str, Any] | None = None) -> str | None:
    """None if the vocabulary was generated for this image; otherwise the reason to refuse."""
    if not image_id:
        return "the target's image could not be identified, so the keyword list cannot be trusted for it"
    if image_id not in image_ids(vocab):
        return ("the keyword list was generated for a different image than the one this container runs; "
                "re-run testbed/scripts/probe_keywords.sh")
    return None


def kind(token: str, context: str, vocab: dict[str, Any] | None = None) -> dict[str, Any] | None:
    """What strongSwan added to a proposal for this keyword in this context
    ({"types": [...], "names": {...}, "aead": bool}), or None if it is not an accepted keyword."""
    if not isinstance(token, str) or not TOKEN_SHAPE.match(token):
        return None
    entry = (vocab or load_vocab())["keywords"].get(token)
    if not entry or not entry.get("accepted"):
        return None
    return entry["contexts"].get(context)


def is_keyword(token: str, context: str, vocab: dict[str, Any] | None = None) -> bool:
    return kind(token, context, vocab) is not None


def ike_evidence(token: str, vocab: dict[str, Any] | None = None) -> list[dict[str, Any]] | None:
    """For an IKE-proposal keyword: [{attribute, value, source}] of what TunnelScope reported on a
    capture where the daemon negotiated the same algorithm. None if any of the algorithms this
    keyword stands for was never observed (so its effect on a rule cannot be checked)."""
    v = vocab or load_vocab()
    k = kind(token, "ike", v)
    if k is None:
        return None
    out = []
    for typ, names in k["names"].items():
        for name in names:
            key = f"KE{typ[3:]}_{name}" if typ.startswith("ake") else name
            ev = v["evidence"]["ike"].get(key)
            if ev is None:
                return None
            out.append(ev)
    return out


def line_evidence(line_key: str, value: str, vocab: dict[str, Any] | None = None) -> list[dict[str, Any]] | None:
    """For a whole ESP/AH proposal value (e.g. "aes256gcm16"): what TunnelScope reported on the
    captures configured with exactly that value. None if never observed."""
    v = vocab or load_vocab()
    return v["evidence"].get(line_key, {}).get(value)
